<h1>Произошла ошибка</h1>
<h2><?= $this->message ?></h2>

<?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>

<?php if(isset($this->exception) && ($this->exception instanceof Exception || $this->exception instanceof Error)): ?>
<hr/>
<h2>Дополнительная информация:</h2>
<h3><?= get_class($this->exception) ?></h3>
<dl>
    <dt>Файл:</dt>
    <dd>
        <pre class="prettyprint linenums"><?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?></pre>
    </dd>
    <dt>Сообщение:</dt>
    <dd>
        <pre class="prettyprint linenums"><?= $this->escapeHtml($this->exception->getMessage()) ?></pre>
    </dd>
    <dt>Отладка:</dt>
    <dd>
        <pre class="prettyprint linenums"><?= $this->escapeHtml($this->exception->getTraceAsString()) ?></pre>
    </dd>
</dl>
<?php
    $e = $this->exception->getPrevious();
    $icount = 0;
    if ($e) :
?>
<hr/>
<h2>Предыдущие исключения:</h2>
<ul class="unstyled">
    <?php while($e) : ?>
    <li>
        <h3><?= get_class($e) ?></h3>
        <dl>
            <dt>File:</dt>
            <dd>
                <pre class="prettyprint linenums"><?= $e->getFile() ?>:<?= $e->getLine() ?></pre>
            </dd>
            <dt>Message:</dt>
            <dd>
                <pre class="prettyprint linenums"><?= $this->escapeHtml($e->getMessage()) ?></pre>
            </dd>
            <dt>Stack trace:</dt>
            <dd>
                <pre class="prettyprint linenums"><?= $this->escapeHtml($e->getTraceAsString()) ?></pre>
            </dd>
        </dl>
    </li>
    <?php
        $e = $e->getPrevious();
        $icount += 1;
        if ($icount >= 50) {
            echo "<li>Возможно произошло больше ошибок, но не хватает памяти, чтобы их воспроизвести.</li>";
            break;
        }
        endwhile;
    ?>
</ul>
<?php endif; ?>

<?php else: ?>

<h3>Исключение недоступно</h3>

<?php endif ?>

<?php endif ?>
