<div class="jumbotron">
    <h1>Приветствуем Вас на<br /> <span class="zf-green">Zend Framework</span></h1>

    <p>
        Поздравляем! Вы успешно установили
        <a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">ZF Скелет Приложение</a>.
        Вы используете версию <?= \Portal\Module::VERSION ?>.
        Скелет Приложение можно использовать в качестве начального этапа для постройки вашего программного обеспечения.
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zendframework" target="_blank">Создайте вилку Zend Framework на GitHub &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Следить за разработкой</h3>
            </div>
            <div class="panel-body">
                <p>
                    Zend Framework в активной разработке. Если есть желание следить за прогрессом ZF, можно просмотреть
                    <a href="http://framework.zend.com/blog/">ZF блог разработки</a>,
                    и <a href="https://github.com/issues?utf8=%E2%9C%93&q=is:issue+org:zendframework">ZF систему отслеживания ошибок</a>
                    (нужен аккаунт на GitHub). Это отличный ресурс
                    узнать, что происходит в организации, над чем работают разработчики, а так-же сообщить о неполадках.
                </p>

                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/" target="_blank">ZF Официальный Портал &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Найдите полезные модули</h3>
            </div>
            <div class="panel-body">
                <p>
                    ZF общество работает над сайтом для репозитории и галереи модулей от 3-их лиц.
                    Проект расположен <a href="https://github.com/zendframework/modules.zendframework.com">на GitHub</a>.
                    Там есть список модулей добровольцы поделились с коллективом, которые вам могут быть полезны.
                </p>

                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank">Исследовать ZF модули &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Помощь и поддержка</h3>
            </div>
            <div class="panel-body">
                <p>
                    Если нужна помощь или поддержка по разработке с ZF,
                    вы можете соединится с нами по IRC: <a href="irc://irc.freenode.net/zftalk">#zftalk на Freenode</a>.
                    Мы будем очень признательны Вашим отзывам и вопросам об этом выпуске.
                    Так же, можно подписаться на почтовые рассылки и там же задавать вопросы через <a href="http://framework.zend.com/archives/">mailing lists</a>.
                </p>

                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank">Присоединяйтесь по IRC &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
