<div class="row">
    <div class="col-md-3">

        <!-- Иконка Профиля -->
        <div class="box box-primary">
            <div class="box-body box-profile">
                <img class="profile-user-img img-responsive img-circle" src="/img/user4-128x128.jpg" alt="Иконка профиля">

                <h3 class="profile-username text-center">Нина Анатольевна</h3>

                <p class="text-muted text-center">Разработчик ПО</p>

                <ul class="list-group list-group-unbordered">
                    <li class="list-group-item">
                        <b>Разрешённых проблем</b> <a class="pull-right">50</a>
                    </li>
                    <li class="list-group-item">
                        <b>Участий в проблемах</b> <a class="pull-right">100</a>
                    </li>
                    <li class="list-group-item">
                        <b>Подписчиков</b> <a class="pull-right">45</a>
                    </li>
                </ul>

                <a href="#" class="btn btn-primary btn-block"><b>&nbsp;</b></a>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->

        <!-- Обо мне -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Обо мне</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <strong><i class="fa fa-map-marker margin-r-5"></i> Местоположение</strong>

                <p class="text-muted">Таганрог, Ростовская обл.</p>

                <hr>

                <strong><i class="fa fa-pencil margin-r-5"></i> Навыки</strong>

                <p>
                    <span class="label label-danger">UI дезайн</span>
                    <span class="label label-success">кодирование</span>
                    <span class="label label-info">JavaScript</span>
                    <span class="label label-warning">PHP</span>
                    <span class="label label-primary">Node.js</span>
                </p>

                <hr>

                <strong><i class="fa fa-file-text-o margin-r-5"></i> Заметки</strong>

                <p>Люди, которые думают, что ненавидят компьютеры, на самом деле ненавидят плохих программистов.</p>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
    <div class="col-md-9">
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <li><a href="/admin/users/1/activity">Деятельность</a></li>
                <li class="active"><a href="#timeline">Лента времени</a></li>
                <li><a href="/admin/users/1/settings">Настройки</a></li>
                <li><a href="/admin/users/1/groups">Группы и разрешения</a></li>
            </ul>
            <div class="tab-content">
                <div class="active tab-pane" id="timeline">
                    <!-- Лента времени -->
                    <ul class="timeline timeline-inverse">
                        <!-- Ярлык линии времени -->
                        <li class="time-label">
                        <span class="bg-red">
                          10 Фев. 2014
                        </span>
                        </li>
                        <!-- /.timeline-label ярлык времени-->
                        <!-- пункт временной линии-->
                        <li>
                            <i class="fa fa-envelope bg-blue"></i>

                            <div class="timeline-item">
                                <span class="time"><i class="fa fa-clock-o"></i> 12:05</span>

                                <h3 class="timeline-header"><a href="#">Техподдержка</a> прислала вам сообщение</h3>

                                <div class="timeline-body">
                                    Etsy doostang zoodles disqus groupon greplin oooj voxy zoodles,
                                    weebly ning heekya handango imeem plugg dopplr jibjab, movity
                                    jajah plickers sifteo edmodo ifttt zimbra. Babblely odeo kaboodle
                                    quora plaxo ideeli hulu weebly balihoo...
                                </div>
                                <div class="timeline-footer">
                                    <a class="btn btn-primary btn-xs">Прочесть полную версию</a>
                                    <a class="btn btn-danger btn-xs">Удалить</a>
                                </div>
                            </div>
                        </li>
                        <!-- КОНЕЦ пункта временной линии -->
                        <!-- пункт временной линии -->
                        <li>
                            <i class="fa fa-user bg-aqua"></i>

                            <div class="timeline-item">
                                <span class="time"><i class="fa fa-clock-o"></i> 5 минут назад</span>

                                <h3 class="timeline-header no-border"><a href="#">Дмитрий Иванов</a> вступил в группу разроботчиков баз данных.
                                </h3>
                            </div>
                        </li>
                        <!-- КОНЕЦ пункта временной линии -->
                        <!-- пункт временной линии -->
                        <li>
                            <i class="fa fa-comments bg-yellow"></i>

                            <div class="timeline-item">
                                <span class="time"><i class="fa fa-clock-o"></i> 27 минут назад</span>

                                <h3 class="timeline-header"><a href="#">Инга Уварова</a> прокомментировл в задаче</h3>

                                <div class="timeline-body">
                                    Миграции нуждаются в пробном запуске и приличного UI. Но да, тоже не могу представить
                                    как из этого сделать полезный урок.
                                </div>
                                <div class="timeline-footer">
                                    <a class="btn btn-warning btn-flat btn-xs">Перейти к задаче</a>
                                </div>
                            </div>
                        </li>
                        <!-- КОНЕЦ пункта временной линии -->
                        <!-- ярлык временной линии -->
                        <li class="time-label">
                        <span class="bg-green">
                          3 Янв. 2014
                        </span>
                        </li>
                        <!-- /.timeline-label ярлык-->
                        <!-- пункт временной линиии -->
                        <li>
                            <i class="fa fa-camera bg-purple"></i>

                            <div class="timeline-item">
                                <span class="time"><i class="fa fa-clock-o"></i> 2 дня назад</span>

                                <h3 class="timeline-header"><a href="#">Тимофей Калинин</a> загрузил новые эскизы</h3>

                                <div class="timeline-body">
                                    <img src="/img/150x100.png" alt="..." class="margin">
                                    <img src="/img/150x100.png" alt="..." class="margin">
                                    <img src="/img/150x100.png" alt="..." class="margin">
                                    <img src="/img/150x100.png" alt="..." class="margin">
                                </div>
                            </div>
                        </li>
                        <!-- КОНЕЦ пункта временной линии -->
                        <!-- END timeline item -->
                        <li>
                            <i class="fa fa-clock-o bg-gray"></i>
                        </li>
                    </ul>
                </div>
                <!-- /.tab-pane вкладка-->
            </div>
            <!-- /.tab-content содержание -->
        </div>
        <!-- /.nav-tabs-custom вкладка нивигиции-->
    </div>
    <!-- /.col колонка-->
</div>
<!-- /.row строка-->