<div class="box">
    <div class="box-header">
        <h3 class="box-title">Список групп</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
            <tr>
                <th><input type="checkbox" title="Все"/></th>
                <th>Наименование</th>
                <th>Прямых участников</th>
                <th>Итого пользователей</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td></td>
                <td><a href="/admin/groups/1/view">Админ</a></td>
                <td>1</td>
                <td>1</td>
            </tr>
            <tr>
                <td></td>
                <td>Пользователи</td>
                <td>0</td>
                <td>12</td>
            </tr>
            <tr>
                <td></td>
                <td>Разработчики</td>
                <td>4</td>
                <td>10</td>
            </tr>
            <tr>
                <td></td>
                <td>Разработчики PHP</td>
                <td>3</td>
                <td>6</td>
            </tr>
            <tr>
                <td></td>
                <td>Разработчики Zend Framework</td>
                <td>3</td>
                <td>3</td>
            </tr>
            <tr>
                <td></td>
                <td>Дизайнеры</td>
                <td>2</td>
                <td>2</td>
            </tr>
            </tbody>
        </table>
    </div>
</div>