<div class="row">
    <div class="col-md-3">

        <!-- Иконка Профиля -->
        <div class="box box-primary">
            <div class="box-body box-profile">
                <img class="profile-user-img img-responsive img-circle" src="/img/user4-128x128.jpg" alt="Иконка профиля">

                <h3 class="profile-username text-center">Нина Анатольевна</h3>

                <p class="text-muted text-center">Разработчик ПО</p>

                <ul class="list-group list-group-unbordered">
                    <li class="list-group-item">
                        <b>Разрешённых проблем</b> <a class="pull-right">50</a>
                    </li>
                    <li class="list-group-item">
                        <b>Участий в проблемах</b> <a class="pull-right">100</a>
                    </li>
                    <li class="list-group-item">
                        <b>Подписчиков</b> <a class="pull-right">45</a>
                    </li>
                </ul>

                <a href="#" class="btn btn-primary btn-block"><b>&nbsp;</b></a>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->

        <!-- Обо мне -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Обо мне</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <strong><i class="fa fa-map-marker margin-r-5"></i> Местоположение</strong>

                <p class="text-muted">Таганрог, Ростовская обл.</p>

                <hr>

                <strong><i class="fa fa-pencil margin-r-5"></i> Навыки</strong>

                <p>
                    <span class="label label-danger">UI дезайн</span>
                    <span class="label label-success">кодирование</span>
                    <span class="label label-info">JavaScript</span>
                    <span class="label label-warning">PHP</span>
                    <span class="label label-primary">Node.js</span>
                </p>

                <hr>

                <strong><i class="fa fa-file-text-o margin-r-5"></i> Заметки</strong>

                <p>Люди, которые думают, что ненавидят компьютеры, на самом деле ненавидят плохих программистов.</p>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
    <div class="col-md-9">
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <li><a href="/admin/users/1/activity">Деятельность</a></li>
                <li><a href="/admin/users/1/timeline">Лента времени</a></li>
                <li class="active"><a href="#settings">Настройки</a></li>
                <li><a href="/admin/users/1/groups">Группы и разрешения</a></li>
            </ul>
            <div class="tab-content">
                <div class="active tab-pane" id="settings">
                    <form class="form-horizontal">
                        <div class="form-group">
                            <label for="inputName" class="col-sm-2 control-label">Имя</label>

                            <div class="col-sm-10">
                                <input type="email" class="form-control" id="inputName" placeholder="Имя">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputName" class="col-sm-2 control-label">Фамилия</label>

                            <div class="col-sm-10">
                                <input type="email" class="form-control" id="inputName" placeholder="Фамилия">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputName" class="col-sm-2 control-label">Отчество</label>

                            <div class="col-sm-10">
                                <input type="email" class="form-control" id="inputName" placeholder="Отчество">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail" class="col-sm-2 control-label">Email</label>

                            <div class="col-sm-10">
                                <input type="email" class="form-control" id="inputEmail" placeholder="Email">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputSkills" class="col-sm-2 control-label">Навыки</label>

                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="inputSkills" placeholder="Навыки">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputExperience" class="col-sm-2 control-label">Заметки</label>

                            <div class="col-sm-10">
                                <textarea class="form-control" id="inputExperience" placeholder="Заметки"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox"> Подписаться на оповещания через электронную почту.
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-danger">Сохранить</button>
                                <button type="submit" class="btn btn-info">Отменить</button>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- /.tab-pane вкладка-->
            </div>
            <!-- /.tab-content содержание -->
        </div>
        <!-- /.nav-tabs-custom вкладка нивигиции-->
    </div>
    <!-- /.col колонка-->
</div>
<!-- /.row строка-->